name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest

    steps:

      - name: Test
        run: |
          echo "message ${{ github.event.head_commit.message }}"
          echo "author ${{ github.event.head_commit.author.name }}" 
          echo "timestamp ${{ github.event.head_commit.timestamp }}"
          echo "sha ${{ github.event.after }}"
          echo "id ${{ github.event.head_commit.id }}"
          echo "url ${{ github.event.head_commit.url }}"
          echo "added ${{ join(github.event.head_commit.added, ',') }}"
          echo "removed ${{ join(github.event.head_commit.removed, ',') }}"
          echo "modified ${{ join(github.event.head_commit.modified, ',') }}"