name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest

    steps:

      - name: Test1
        id: test1
        run: |
          echo "commits_count=$(echo "$(( 1 + $(echo "${{ join(github.event.commits.*.id, ',') }}" | tr ',' '\n' | grep -c '')))")" >> $GITHUB_OUTPUT

      - name: Test2
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: ${{ steps.test1.outputs.commits_count }}

      - name: Test3
        run: |
          mkdir ../output
          git config diff.renames false

      # - name: Test
      #   run: |
      #     echo "message ${{ github.event.head_commit.message }}"
      #     echo "author ${{ github.event.head_commit.author.name }}" 
      #     echo "timestamp ${{ github.event.head_commit.timestamp }}"
      #     echo "sha ${{ github.event.after }}"
      #     echo "id ${{ github.event.head_commit.id }}"
      #     echo "url ${{ github.event.head_commit.url }}"
      #     echo "added ${{ join(github.event.head_commit.added, ',') }}"
      #     echo "removed ${{ join(github.event.head_commit.removed, ',') }}"
      #     echo "modified ${{ join(github.event.head_commit.modified, ',') }}"
      #     echo "modified ${{ join(github.event.head_commit.aaaaaa, ',') }}"
      #     echo "${{ toJSON(github.event.commits) }}"
      #     # cat $GITHUB_EVENT_PATH

      - name: Commits
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
          BEFORE_ID: ${{ github.event.before }}
        run: |
          .github/workflows/commits.sh

      # - name: Message
      #   env:
      #     ABCDEF: ${{ secrets.ABCDEF }}
      #     ROOM_ID: ${{ secrets.ROOM_ID }}
      #     MESSAGE: ${{ github.event.head_commit.message }}
      #     AUTHOR: ${{ github.event.head_commit.author.name }}
      #   rum: |
      #     .github/workflows/message.sh